version: 0.2

phases:
  install:
    runtime-versions:
      java: amazoncorretto21
  build:
    commands:
      - echo "Building the application"
      - mvn clean package
artifacts:
  files:
    - target/spring-boot-docker-complete-0.0.1-SNAPSHOT.jar
